import { SiteConfig } from "@/types";

import { absoluteUrl } from "@/lib/utils";

export const siteConfig: SiteConfig = {
  name: "Kyaw Thet Paing",
  title: "Kyaw Thet Paing • Software Engineer",
  description:
    "Discover my world of software development expertise through a portfolio of innovative projects and meticulously crafted code.",
  url: absoluteUrl(),
  ogImage: absoluteUrl("/og.jpg"),
  authors: [
    { name: "@ikyawthetpaing", url: "https://twitter.com/ikyawthetpaing" },
  ],
  creator: "@ikyawthetpaing",
  keywords: [
    "Freelance Software Developer",
    "Software Development Services",
    "Custom Software Development",
    "Web Application Development",
    "Mobile App Development",
    "Software Engineer for Hire",
    "Frontend Development",
    "Backend Development",
    "Full Stack Developer",
    "UI/UX Design and Development",
    "Database Development",
    "API Integration",
    "E-commerce Development",
    "Responsive Web Design",
    "WordPress Development",
    "Java Developer",
    "Python Developer",
    "JavaScript Developer",
    "React.js Developer",
    "Node.js Developer",
    "PHP Developer",
    "Mobile App Developer",
    "Database Management",
    "Cloud Computing Solutions",
    "Software Maintenance and Support",
    "Agile Software Development",
    "Freelance Programmer",
    "Software Prototyping",
    "Code Optimization",
    "Software Consulting Services",
    "Web Development",
    "Full-Stack Development",
    "Front-End Development",
    "Back-End Development",
    "Software Architecture",
    "Game Development",
    "DevOps and Deployment",
    "Machine Learning and AI",
    "Open Source Contributions",
    "Version Control Systems",
    "Problem Solving",
    "Algorithm Design and Optimization",
    "Debugging and Testing",
    "Continuous Integration and Deployment (CI/CD)",
    "Security Protocols and Encryption",
    "Data Structures and Algorithms",
    "Collaboration and Teamwork",
  ],
};
